### ISSUE TITLE
New dataset request : Paracrawl_v8

### ISSUE THREAD

**Issue by kirianguiller** [thammegowda/mtdata#29]
Hi again 

As discussed on the [translatelocally discourse](https://discourse.translatelocally.com/t/mtdata-corpus-needed/15), it would be nice to have the Paracrawl_v8 corpus in mtdata. Is it a more complicated if the corpus is not already on Opus repertoire ?

Thanks

**Comment by kpu** [comment]
I'm embarrassed by the current URL scheme on the home page, caused largely by the Internet Archive imposing a 1 TB limit per directory.  

However, the files are also where you expect them to be e.g. https://s3.amazonaws.com/web-language-models/paracrawl/release8/en-es.txt.gz .  

Note that the Internet Archive offered permanent storage instead of renewal every 2 years from AWS so at least the Internet Archive URLs are permanent.

**Comment by thammegowda** [comment]
Thanks for creating this. 

> Is it more complicated if the corpus is not already on Opus repertoire?

Not really. We have been fetching Paracrawl directly from `https://s3.amazonaws.com/web-language-models/paracrawl/release6/` so far:
 https://github.com/thammegowda/mtdata/blob/master/mtdata/index/paracrawl.py 
 
 So this will be an easy addition.
